### PR TITLE
Add datomic-cloud/generate-resolvers-pathom3

### PR DESCRIPTION
**Pull request by danieroux**
Tony, 

This is our best effort to add `datomic-cloud/generate-resolvers-pathom3`.

The challenge is that pathom3 resolvers bottom out as `com.wsscode.pathom3.connect.operation/Resolver` defrecords. So we have to invoke `com.wsscode.pathom3.connect.operation/resolver`.

We did this using `requiring-resolve` to not add the dependency.

### CODE REVIEW

**Comment by awkay** [comment]
Thanks for the effort. I'm wondering if you'd be willing to do the on-prem change as well so that the library remains balanced? And also could you squash the commits to a single commit with a good commit message that indicates the changes in a changelog sort of way?

**Comment by danieroux** [comment]
Here is a much more aggressive change, pulling all the common code out and balancing on-prem and cloud

**Comment by awkay** [comment]
Ooops. 

OK, so public functions can move, but ONLY if you leave a def in the old location (with a docstring that maintains the arglist (has to be manually entered since def doesn't show arglist), and also contains a deprecation note and a comment about new location in the docstring). Otherwise it is a library breaking change, even if that function is not used by the library itself. Also cannot change signatures or require more. So, I appreciate the increased effort, but I cannot merge that as-is.

Also, creating *new* public vars like `(def the-pull-fn d/pull)` is not something I like to see. Those will show up in autocomplete, become intractable (because they are public; see prior paragraph), and don't really add anything...you already have vars for those things under a short alias.

**Comment by danieroux** [comment]
Thank you for your clear feedback and responsiveness Tony!

I now want to get #17 into a shape that you are happy with. Then add the pathom3 work on top of that.

**Comment by awkay** [comment]
OK, so you want to do #17, then come back to this?

**Comment by danieroux** [comment]
Yes, #17 does not (should not) accrete or be a breaking change. Once that's good, then adding pathom3 should be much cleaner. I hope.

**Comment by awkay** [comment]
ok, all done.

**Comment by danieroux** [comment]
Here then, is datomic{,-cloud}/generate-resolvers-pathom3 

The tests pass for pathom3 against on-prem.

I notice the parser integration specification for cloud is/was exactly the same. I did not do the work to make pathom3 run against that as well.

**Comment by awkay** [comment]
Nicely done. Thanks!

**Pull request merged**
